require:
  - rubocop-rspec

AllCops:
  AllowSymlinksInCacheRootDirectory: true
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 3.0
  SuggestExtensions: false

# Offense count: 1
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  Exclude:
    - spec/**/*

# Offense count: 1
# Configuration parameters: ExpectMatchingDefinition, Regex, IgnoreExecutableScripts, AllowedAcronyms.
Naming/FileName:
  Exclude:
    - 'lib/rubocop-sequel.rb'
